### ISSUE TITLE
[Mobile] Fail cases of voucher buying aren't having correct Error message in Application

### ISSUE THREAD

**Issue by Mamyako** [OpenMAVN/PM#127] opened 2020-05-21 13:24 UTC
**Environment:** iOS software version 13.4.1/ Android software version 10

**Note:** related to #29 ticket
**Cases:**
1. SmartVouchers component can't reserve a voucher for required campaign.
2. Payrexx is unavailable

**Note for case 1:** When last remaining voucher is available for some campaign, then reservation flow should be started from 2 customer accounts

**Steps for case 1:**

1. Log in to mobile application as a customer using credentials
2. Tap offers tab at the bottom menu of the application
3. Tap to any available voucher with only one voucher left
4. Tap Redeem offer button from two accounts 

**Actual result:** User that tapped later see error message "Oops! It look like something went wrong. If the issue continues, contact our friendly customer service"
**Expected result:**  User that tapped later see error message "Smart voucher campaign does not have available vouchers"

**Precondition for case 1:** Payrexx is unavailable

**Steps for case 2:**

1. Log in to mobile application as a customer using credentials
2. Tap offers tab at the bottom menu of the application
3. Tap any available voucher
4. Tap Redeem offer button

**Actual result:** User that tapped later see error message "Oops! It look like something went wrong. If the issue continues, contact our friendly customer service"
**Expected result:** User that tapped later see error message "There's a problem with payment provider"
![19.jpg](https://images.zenhubusercontent.com/5ebd4a65073213c8e8f366ea/a7590207-6c3c-49d0-9edd-d7e08f415354)

**Comment by Mamyako** [comment] 2020-05-21 13:25
@ElenaBelyavskaya please, review the description

**Comment by pddimitrova** [comment] 2020-05-21 14:15
@Mamyako Where (in which story) are these message requirements described?

**Comment by Mamyako** [comment] 2020-05-21 14:19
@pddimitrova Messages should be different but their text isn't confirmed for now, that's why need some review from @ElenaBelyavskaya

**Comment by pddimitrova** [comment] 2020-05-21 14:25
@Mamyako Then this is not a bug rather than a regular story for adding messages that had not previously existed.

**Comment by Mamyako** [comment] 2020-05-21 14:27
Sure, I'll change label

**Comment by pddimitrova** [comment] 2020-05-26 07:01
@ElenaBelyavskaya @MarlonMaercz In order that we move this to Ready for development, we will need copies for such cases

**Comment by ElenaBelyavskaya** [comment] 2020-06-04 12:48
@pddimitrova for now added the texts to https://docs.google.com/spreadsheets/d/1e38PERmWzvvK777QtuBPEFm1jAa_lVZZ/edit#gid=382811706, rows 599 and 600

**Comment by pddimitrova** [comment] 2020-06-04 13:06
@ElenaBelyavskaya These are the errors we need messages for:
SmartVoucherCampaignNotFound
SmartVoucherCampaignNotActive
NoAvailableVouchers
PaymentProviderError
SmartVoucherNotFound
CustomerHaveAnotherReservedVoucher

I can create a mobile subtask as soon as we have the copies.

**Comment by ElenaBelyavskaya** [comment] 2020-06-04 14:05
@pddimitrova 2 of these errors are mentioned in the story already (NoAvailableVouchers, PaymentProviderError)
- SmartVoucherCampaignNotActive - In this case voucher should not be available to buy, so basically the text of the error is not required (right now Not Active offers are not even displayed in the offer list).
- SmartVoucherCampaignNotFound, SmartVoucherNotFound - what is the difference between these 2 cases? With _campaign not found_ - probably it's when a campaign is deleted; then again, the voucher should not be available to buy.
- CustomerHaveAnotherReservedVoucher - If a customer already have a reserved voucher, the customer should not be able to reserve another instance of this voucher (this is another story, #165); the customer would not be able to buy another instance of voucher - only to finalize purchase of the already reserved voucher. In that story we will have a hint for the user, but the error text is not needed right now.

**Comment by pddimitrova** [comment] 2020-06-17 06:30
The errors with provided error message are handled. CustomerHaveAnotherReservedVoucher will be handled in #165. Closing this.

**Closed as completed by pddimitrova** 2020-06-17 06:30 UTC
Labels: Mobile, Epic, Tech story, Mobile UI
