### ISSUE TITLE
As a customer I want to see details of bought smart vouchers in mobile app

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/PM#53] opened 2020-04-20 16:51 UTC
As a customer I want to see details of bought smart vouchers in mobile app. This is a follow up story to #57 

For this feature we should have a page in mobile app that will show a list of bought smart vouchers.*
1. On a voucher entry click it must show a page with smart voucher details:
- image of the voucher campaign
- short code as a unique identifier
- voucher campaign name
- voucher campaign owner (partner)
- expiration date (end of campaign)
- price
- date of purchase
- validation QR code
---
* Current Vouchers screen under My Account

Subtasks:
1. openmavn/mavn.service.customerapi#3
2. openmavn/mavn.service.customerapi#14
3. openmavn/mavn.mobile#35
4. OpenMAVN/MAVN.Service.SmartVouchers#32

**Comment by starkmsu** [comment] 2020-04-20 17:46
@MarlonMaercz , @ElenaBelyavskaya , @pddimitrova , please review the story description

**Comment by Mamyako** [comment] 2020-05-22 11:05
@pddimitrova  Can't see short code as a unique identifier, date of purchase, literal validation code. Expiration date (end of campaign) can't be seen only on Android, iOS is okay with that, but also need some improvement because it doesn't fit well for long names of vouchers 
![image](https://user-images.githubusercontent.com/65350611/82661737-3b481180-9c35-11ea-8974-30af270fe7a4.png)

**Comment by pddimitrova** [comment] 2020-05-26 08:17
@Mamyako These are visual bugs that can be fixed with a Bug/ Enhancement ticket. The fields that are missing are not there by design, so the mobile app representation is accurate to the design. If they must be added, a new story will be created with the new design

**Comment by ElenaBelyavskaya** [comment] 2020-05-27 06:57
@pddimitrova I will ask Maria to prep design mockup with missing fields (required in the desc)

**Comment by pddimitrova** [comment] 2020-05-29 14:34
@MarlonMaercz @ElenaBelyavskaya Do we really need to show validation code literal( in ticket description)? The user cannot use it in any way, so it’s just going to take up space and bring 0 value.
Same applies to short code. How can the user benefit from seeing it?

**Comment by MarlonMaercz** [comment] 2020-05-29 14:41
@pddimitrova Agreed, we do not need to show the literal code. You can leave it out. I've created a separate Github Issue for the edge case where it could be required (#157)

**Comment by ElenaBelyavskaya** [comment] 2020-05-29 18:49
We need literal code (as alternative when QR code is not working for some reason) but if it can't be applied as a function right now, I agree with @MarlonMaercz that it should be done under additional story.

**Comment by Mamyako** [comment] 2020-06-01 13:38
I faced a problem with positioning of expiration date and date of purchase in 2 columns, they can be read in a row and it looks like there's no date of purchase 
![image](https://user-images.githubusercontent.com/65350611/83414496-50d3ed00-a426-11ea-8aca-5d4d00aa24b0.png)

**Closed as completed** 2020-06-03 11:43 UTC
Labels: Backend, Mobile, User story, Smart Vouchers
